services:
  - type: web
    name: openfreeocr
    runtime: node
    plan: free
    buildCommand: bun install --frozen-lockfile && bun run build
    startCommand: bun run start -- -H 0.0.0.0 -p $PORT
    autoDeployTrigger: commit
    domains:
      - openfreeocr.online
    renderSubdomainPolicy: disabled
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: BUN_VERSION
        value: "1.3.10"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NVIDIA_API_KEY
        sync: false
